spring:
  application:
    name: build-number-generator
    version: ${applicationVersion}
java:
  version: ${javaVersion}

rocksdb:
  path: out/rocksdb

logging:
  level:
    org.springframework.cache: TRACE