name: Setup Gradle
description: Setup Gradle for the build process.

inputs:
  java-version:
    description: The version of Java to set up.
    required: true
    default: '21'
  gradle-cache-path:
    description: Path to cache Gradle dependencies.
    required: true
    default: ~/.gradle/caches
runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ${{ inputs.gradle-cache-path }}
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permissions to Gradle wrapper
      id: gradle_permissions
      shell: bash
      run: chmod +x ./gradlew
