apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-number-generator-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: longhorn