apiVersion: v1
kind: Service
metadata:
  name: build-number-generator-service
  labels:
    app: build-number-generator
spec:
  selector:
    app: build-number-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP